swagger: "2.0"
info:

  version: "1.0"

  title: "Calendar API"

tags:
- name: "notification-service"
  description: "send notifications"
  externalDocs:
    description: "Find out more"
    url: "http://swagger.io"

- name: "event-processing"
  description: "work with calendar user's events data"
  
- name: "user"
  description: "work with user data"


paths:


  /notification-service/telegram/send:

    get:
      tags: 
      - "notification-service"
     
      description: Sends event notification to telegram chat

      parameters:
      
        - name: api-key
          
          in: header
          
          type: string
          
          required: true
          
          description: key to use handle

        - name: chatID

          in: header

          type: string

          required: true

          description: id of telegram chat where to send message.
        
        - name: event data
          
          in: body
          
          schema: 
            
            $ref: "#/definitions/Event" 
          
          required: true
          
          description: data to form notification text
          

      responses:

        200:

          description: notification sent successfully

        400:

          description: Invalid characters in "chatID" were provided.
        
        502:
          
          description: Couldn't get answer from telegram API
        
        500:
        
          description: Error reading request body
 
          
  /notification-service/telegram/confirm:

    get:
      tags: 
      - "notification-service"

      description: Returns a greeting to the user!
      

      parameters:

        - name: chatID

          in: header

          type: string

          required: true

          description: id of telegram chat where to send message.
        
        - name: notification text
          
          in: body
          
          schema: 
            
            type: string
          
          required: true
          
          description: text of notification telegram message
          

      responses:

        200:

          description: Returns chat where message has been sent.

          schema:

            type: integer
            
      deprecated: true


  /notification-service/email/send:

    get:
      tags: 
      - "notification-service"
     
      description: Sends event notification to email address

      parameters:
      
        - name: api-key
          
          in: header
          
          type: string
          
          required: true
          
          description: key to use handle

        - name: email

          in: header

          type: string

          required: true

          description: email adress where to send message.
        
        - name: event data
          
          in: body
          
          schema: 
            
            $ref: "#/definitions/Event" 
          
          required: true
          
          description: data to form notification text
      
      
      responses:

        200:

          description: notification sent successfully
          
        400:

          description: Invalid characters in "email" were provided.
        
        502:
          
          description: Couldn't get answer from email service
        
        500:
        
          description: Error reading request body


  /notification-service/sms/send:

    get:
      tags: 
      - "notification-service"
     
      description: Sends event notification to sms

      parameters:
      
        - name: api-key
          
          in: header
          
          type: string
          
          required: true
          
          description: key to use handle

        - name: phone-number

          in: header

          type: string

          required: true

          description: phone number where to send sms message
        
        - name: event data
          
          in: body
          
          schema: 
            
            $ref: "#/definitions/Event" 
          
          required: true
          
          description: data to form notification text
          

      responses:

        200:

          description: notification sent successfully

        400:

          description: Invalid characters in "chatID" were provided.
        
        502:
          
          description: Couldn't get answer from sms service api
        
        500:
        
          description: Error reading request body

# ---------------------------------------------------------------------------------------
# ----------------------------------EVENT------------------------------------------------
# ---------------------------------------------------------------------------------------

  
  /event-processing/event/add:

    post:
      tags: 
      - "event-processing"

      description: Add event


      parameters:

        - name: notification text
          
          in: body
          
          schema: 
            
            type: string
          
          required: true
          
          description: text of notification telegram message
          

      responses:

        200:

          description: Returns chat where message has been sent.

          schema:

            type: integer

        400:

          description: Invalid characters in "chatID" were provided.
        
        502:
          
          description: Couldn't get answer from telegram API
        
        500:
        
          description: Error reading request body
          
          
  /event-processing/event/update:

    patch:
      tags: 
      - "event-processing"

      description: Update event information


      parameters:

        - name: event data
          
          in: body
          
          schema: 
            
            $ref: "#/definitions/Event" 
          
          required: true
          
          description:  event data for update
          

      responses:

        200:

          description: Returns chat where message has been sent.

          schema:

            type: integer

        400:

          description: Invalid characters in "chatID" were provided.
        
        502:
          
          description: Couldn't get answer from telegram API
        
        500:
        
          description: Error reading request body

  
  /event-processing/event/delete:

    delete:
      tags: 
      - "event-processing"

      description: Delete event


      parameters:

        - name: event_title

          in: header

          type: integer

          required: true

          description: id of telegram chat where to send message.
        
        - name: token
          
          in: header
          
          type: string
          
          required: true
          
          description: user's token
          

      responses:

        200:

          description: Returns chat where message has been sent.


        400:

          description: Invalid token
        
        502:
          
          description: Couldn't get answer from database
        
        500:
        
          description: Error reading request headers
          

  /event-processing/event/all:

    get:
      tags: 
      - "event-processing"

      description: Get all events of user


      parameters:

        - name: userName

          in: header

          type: integer

          required: true

          description: id of user
        
        - name: notification text
          
          in: body
          
          schema: 
            
            type: string
          
          required: true
          
          description: text of notification telegram message
          

      responses:

        200:

          description: Returns chat where message has been sent.

          schema:

            type: integer

        400:

          description: Invalid characters in "chatID" were provided.
        
        502:
          
          description: Couldn't get answer from telegram API
        
        500:
        
          description: Error reading request body
          
      

  /event-processing/user/workload/{userName}:

    get:
      tags: 
      - "event-processing"

      description: Get interval of free and occupied user time


      parameters:

        - name: userName

          in: path

          type: integer

          required: true

          description: id of user
        
        - name: date
          
          in: header
          
          
          type: integer
          
          required: true
          
          description: date of users load
    

      responses:

        200:

          description: Returns intervals of occupied time.

          schema:

            type: integer

        400:

          description: Invalid characters in "chatID" were provided.
        
        502:
          
          description: Couldn't get answer from telegram API
        
        500:
        
          description: Error reading request body        


#------------------------------------------------------------------------------------------
#------------------------------USER DATA---------------------------------------------------
#------------------------------------------------------------------------------------------


  /user/register:

    put:
      tags: 
      - "user"

      description: Register new user


      parameters:

        
        - name: user data
          
          in: body
          
          schema:
            $ref: "#/definitions/User" 
              
          
          required: true
          
          description: text of notification telegram message
          

      responses:

        200:

          description: User registered


        400:

          description: Invalid user data provided for registration
        
        502:
          
          description: Couldn't get answer from database
        
        500:
        
          description: Error reading request body        



  /user/authentication-token:

    get:
      tags: 
      - "user"

      description: User login


      parameters:

        
        - name: notification text
          
          in: body
          
          schema: 
            
            type: string
          
          required: true
          
          description: text of notification telegram message
          

      responses:

        200:

          description: Returns chat where message has been sent.

          schema:

            type: integer

        400:

          description: Invalid characters in "chatID" were provided.
        
        502:
          
          description: Couldn't get answer from telegram API
        
        500:
        
          description: Error reading request body
          
          
#--------------------------------------------------------------------------
# ------------------Models-------------------------------------------------
#--------------------------------------------------------------------------

definitions:

  User:
    type: "object"
    properties:
      password:
        type: "string"
      email:
        type: "string"
      phoneNumber:
        type: "string"
      telegramID:
        type: "string"
      name:
        type: "string"
      surname:
        type: "string"
 

  Event:
    type: "object"
    properties:
      beginTime:
        type: "string"
        format: "datetime"
      endTime:
        type: "string"
        format: "datetime" 
      description:
        type: "string"
        format: "TEXT"
      meetingLink:
        type: "string"
        format: "link"
      isRepeating:
        type: "boolean"
      title:
        type: "string"
        
        
  EventParticipant:
    type: "object"
    properties:
      eventParticipantID:
        type: "integer"
        format: "int64"
      eventID:
        type: "integer"
        format: "int64"
      userID:
        type: "integer"
        format: "int64"
      isGoing:
        type: "boolean"
      notificationTime:
        type: "string"
      notificationInTelegram:
        type: "boolean"
      notificationInEmail:
        type: "boolean"
      notificationInSMS:
        type: "boolean"

  UserWorkload:
    type: "array"
    items:
      type: "object"
      properties:
        beginTime:
          type: "string"
          format: "time"
        endTime:
          type: "string"
          format: "time"
        