swagger: "2.0"
info:

  version: "1.0"

  title: "Calendar API"

tags:
- name: "notify"
  description: "send notifications"
  externalDocs:
    description: "Find out more"
    url: "http://swagger.io"

- name: "event"
  description: "work with calendar events data"
  
- name: "user"
  description: "work with user data"


paths:


  /notify/telegram/{chatID}:

    get:
      tags: 
      - "notify"
     
      description: Sends event notification to telegram chat

      parameters:

        - name: chatID

          in: path

          type: integer

          required: true

          description: id of telegram chat where to send message.
        
        - name: notification text
          
          in: body
          
          schema: 
            
            type: string
          
          required: true
          
          description: text of notification telegram message
          

      responses:

        200:

          description: Returns chat where message has been sent.

          schema:

            type: integer

        400:

          description: Invalid characters in "chatID" were provided.
        
        502:
          
          description: Couldn't get answer from telegram API
        
        500:
        
          description: Error reading request body
 

          
  /confirm/telegram/{chatID}:

    get:
      tags: 
      - "notify"

      description: Returns a greeting to the user!


      parameters:

        - name: chatID

          in: path

          type: integer

          required: true

          description: id of telegram chat where to send message.
        
        - name: notification text
          
          in: body
          
          schema: 
            
            type: string
          
          required: true
          
          description: text of notification telegram message
          

      responses:

        200:

          description: Returns chat where message has been sent.

          schema:

            type: integer

 
# ----------------------------------EVENT--------------------------------------------------------------------------
  
  /event/add:

    post:
      tags: 
      - "event"

      description: Add event


      parameters:

        - name: notification text
          
          in: body
          
          schema: 
            
            type: string
          
          required: true
          
          description: text of notification telegram message
          

      responses:

        200:

          description: Returns chat where message has been sent.

          schema:

            type: integer

        400:

          description: Invalid characters in "chatID" were provided.
        
        502:
          
          description: Couldn't get answer from telegram API
        
        500:
        
          description: Error reading request body
          

  
  /event/delete/{eventID}:

    delete:
      tags: 
      - "event"

      description: Delete event


      parameters:

        - name: eventID

          in: path

          type: integer

          required: true

          description: id of telegram chat where to send message.
        
        - name: notification text
          
          in: body
          
          schema: 
            
            type: string
          
          required: true
          
          description: text of notification telegram message
          

      responses:

        200:

          description: Returns chat where message has been sent.

          schema:

            type: integer

        400:

          description: Invalid characters in "chatID" were provided.
        
        502:
          
          description: Couldn't get answer from telegram API
        
        500:
        
          description: Error reading request body
          

  /event/getAll/{userID}:

    get:
      tags: 
      - "event"

      description: Get all of user


      parameters:

        - name: userID

          in: path

          type: integer

          required: true

          description: id of user
        
        - name: notification text
          
          in: body
          
          schema: 
            
            type: string
          
          required: true
          
          description: text of notification telegram message
          

      responses:

        200:

          description: Returns chat where message has been sent.

          schema:

            type: integer

        400:

          description: Invalid characters in "chatID" were provided.
        
        502:
          
          description: Couldn't get answer from telegram API
        
        500:
        
          description: Error reading request body
          
       
       
#------------------------------USER DATA---------------------------------------------------       
  /user/getLoad/{userID}:

    get:
      tags: 
      - "user"

      description: Get interval of free and occupied user time


      parameters:

        - name: userID

          in: path

          type: integer

          required: true

          description: id of user
        
        - name: notification text
          
          in: body
          
          schema: 
            
            type: string
          
          required: true
          
          description: text of notification telegram message
          

      responses:

        200:

          description: Returns chat where message has been sent.

          schema:

            type: integer

        400:

          description: Invalid characters in "chatID" were provided.
        
        502:
          
          description: Couldn't get answer from telegram API
        
        500:
        
          description: Error reading request body        


  /user/register:

    put:
      tags: 
      - "user"

      description: Register new user


      parameters:

        
        - name: notification text
          
          in: body
          
          schema: 
            
            type: string
          
          required: true
          
          description: text of notification telegram message
          

      responses:

        200:

          description: Returns chat where message has been sent.

          schema:

            type: integer

        400:

          description: Invalid characters in "chatID" were provided.
        
        502:
          
          description: Couldn't get answer from telegram API
        
        500:
        
          description: Error reading request body        



  /user/authenticationToken:

    get:
      tags: 
      - "user"

      description: User login


      parameters:

        
        - name: notification text
          
          in: body
          
          schema: 
            
            type: string
          
          required: true
          
          description: text of notification telegram message
          

      responses:

        200:

          description: Returns chat where message has been sent.

          schema:

            type: integer

        400:

          description: Invalid characters in "chatID" were provided.
        
        502:
          
          description: Couldn't get answer from telegram API
        
        500:
        
          description: Error reading request body
          

# ------------------Models--------------------------------------------------

definitions:

  User:
    type: "object"
    properties:
      userID:
        type: "integer"
        format: "int64"
      passwordHash:
        type: "string"
      email:
        type: "string"
      phoneNumber:
        type: "string"
      telegramID:
        type: "integer"
      name:
        type: "string"
      surname:
        type: "string"
      avatar:
        type: "string"
  
  Event:
    type: "object"
    properties:
      eventID:
        type: "integer"
        format: "int64"
      beginTime:
        type: "string"
        format: "datetime"
      endTime:
        type: "string"
        format: "datetime" 
      description:
        type: "string"
        format: "TEXT"
      meetingLink:
        type: "string"
        format: "link"
      isRepeating:
        type: "boolean"
        
  EventParticipant:
    type: "object"
    properties:
      eventParticipantID:
        type: "integer"
        format: "int64"
      eventID:
        type: "integer"
        format: "int64"
      userID:
        type: "integer"
        format: "int64"
      isGoing:
        type: "boolean"
      notificationTime:
        type: "string"
      notificationInTelegram:
        type: "boolean"
      notificationInEmail:
        type: "boolean"
      notificationInSMS:
        type: "boolean"
